version: '3.3'

services:

  maven:
    image: 51.250.22.183:8081/boxfuse
    volumes:
      - static:/usr/local/boxfuse-sample-java-war-hello/target/

  tomcat:
    image: tomcat:9.0.0.M15-jre8-alpine
    ports:
      - "80:8080"
    volumes:
      - static:/usr/local/tomcat/webapps

volumes:
  static:
