version: '3.3'

services:

  maven:
    image: 10.129.0.10:8123/boxfuse
    volumes:
      - static:/usr/local/boxfuse-sample-java-war-hello/target/

  tomcat:
    image: tomcat:9.0.0.M15-jre8-alpine
    ports:
      - "80:8080"
    volumes:
      - static:/usr/local/tomcat/webapps

volumes:
  static:
